name: CI
on: [push]
jobs:
  git-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: awseward/git-test-setup@0.1
        with:
          test_name: ci
          test_command: ./test/run.sh all
      - uses: awseward/dhall-setup@main

      - run: git test run --color --test ci
      - run: git push origin 'refs/notes/tests/ci'
